x-restart-policy: &restart_policy
  restart: unless-stopped
x-app-defaults: &app_defaults
  <<: *restart_policy
  stop_grace_period: "3s"
  volumes:
    - ./data:/app/data
  depends_on:
    - redis
    - db
services:
  app:
    <<: *app_defaults
    build: .
    command: make gunicorn
    ports:
      - "${ENTRY_PORT:-15000}:8000"
  celery:
    <<: *app_defaults
    build: .
    command: make celery
  redis:
    <<: *restart_policy
    image: redis:7.4.1-alpine
    volumes:
      - redis_data:/data
  db:
    <<: *restart_policy
    image: postgres:17.0-alpine3.20
    shm_size: 256m
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${SQL_DATABASE:-postgres}
      POSTGRES_USER: ${SQL_USER:-postgres}
      POSTGRES_PASSWORD: ${SQL_PASSWORD:-postgres}
    command: >
      postgres
      -c max_connections=${SQL_MAX_CONNECTIONS:-100}
      -c shared_buffers=${SQL_SHARED_BUFFERS:-128MB}
      -c work_mem=${SQL_WORK_MEM:-4MB}
      -c effective_cache_size=${SQL_EFFECTIVE_CACHE_SIZE:-4GB}
volumes:
  postgres_data:
  redis_data:
