name: App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SECRET_KEY: example-secret-key

jobs:
  backend:
    name: backend test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install requirements
        run: uv sync
      - name: lint
        run: uv run make lint
