name: backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend:
    name: Backend setup
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: example-secret-key

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install Packages
        run: uv sync
      - name: Run migrations
        run: uv run make migrate
      - name: Lint
        run: uv run make lint
      - name: Coverage
        run: uv run make coverage && uv run coverage xml
      - name: Build coverage report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: '60 85'
      - name: Add coverage PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
